- name: 1.部署Docker
  gather_facts: false
  hosts: k8s
  roles:
    - docker 
  tags: docker
- name: 2.自签证书 
  gather_facts: false
  hosts: localhost 
  roles:
    - tls
  tags: tls
- name: 3.部署ETCD集群
  gather_facts: false
  hosts: etcd
  roles:
    -  etcd
  tags: etcd
- name: 4.部署K8S Master
  gather_facts: false
  hosts: master
  roles:
    - master
  tags: master
- name: 5.部署K8S Node
  gather_facts: false
  hosts: node
  roles:
    - node
  tags: node
- name: 6.初始化
  gather_facts: false
  hosts: k8s
  roles:
    - common
  tags: common
- name: 7.部署插件
  gather_facts: false
  hosts: master
  roles:
    - addons
  tags: addons

- name: 8.部署Nginx
  gather_facts: false
  hosts: localhost
  roles:
    - nginx
  tags: nginx
